[[main]]
    name = "Home"
    url = ""
    weight = 1

[[main]]
    name = "Events"
    url = "events/"
    weight = 2

[[main]]
    identifier = "slides"
    name = "Slides"
    url = "slides/"
    weight = 3

[[main]]
    name = "ReleaseNotes"
    url = "releasenotes/"
    weight = 4

[[main]]
    name = "Tags"
    url = "tags"
    weight = 9
